require 'rubygems'
require 'rake/gempackagetask.rb'

spec = Gem::Specification.new do |s|
 s.name = "whistlepig"
 s.version = "0.2"
 s.date = Time.now.to_s
 s.email = "wmorgan-whistlepig-gemspec@masanjin.net"
 s.authors = ["William Morgan"]
 s.summary = "a minimalist realtime full-text search index"
 s.homepage = "http://masanjin.net/whistlepig"
 s.files = %w(README ext/whistlepig/extconf.rb lib/whistlepig.rb) + Dir["ext/whistlepig/*.[ch]"]
 s.extensions = %w(ext/whistlepig/extconf.rb)
 s.executables = []
 s.extra_rdoc_files = %w(README ext/whistlepig/whistlepigc.c)
 s.rdoc_options = %w(-c utf8 --main README --title Whistlepig)
 s.description = "Whistlepig is a minimalist realtime full-text search index. Its goal is to be as small and minimally-featured as possible, while still remaining useful, performant and scalable to large corpora. If you want realtime full-text search without the frills, Whistlepig may be for you."
end

task :rdoc do |t|
  sh "rm -rf doc; rdoc #{spec.rdoc_options.join(' ')} #{spec.extra_rdoc_files.join(' ')} lib/whistlepig.rb"
end

Rake::GemPackageTask.new spec do
end

# vim: syntax=ruby
